<a href="https://colab.research.google.com/github/chetan-ade/FYP/blob/master/WindDir_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive

import numpy as np
import pandas as pd
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Activation, Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.python.keras.utils import np_utils
import datetime
from datetime import date

In [2]:
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [35]:
df = pd.read_csv('gdrive/My Drive/tarapur_preprocessed.csv')
df.head()

Unnamed: 0        date  day  month WindDir  WindspeedKmph
0           0  2008-07-01    1      7      SW             25
1           1  2008-07-02    2      7      SW             26
2           2  2008-07-03    3      7      SW             22
3           3  2008-07-04    4      7      SW             22
4           4  2008-07-05    5      7      SW             22

In [0]:
data = pd.DataFrame(
    columns=['day', 'month', 'WindDir']
)

In [37]:
data['day'] = df['day']
data['month'] = df['month']
data['WindDir'] = df['WindDir']
data.head()

day  month WindDir
0    1      7      SW
1    2      7      SW
2    3      7      SW
3    4      7      SW
4    5      7      SW

In [38]:
data.describe()

day        month
count  4290.000000  4290.000000
mean     15.724009     6.556876
std       8.798265     3.476216
min       1.000000     1.000000
25%       8.000000     3.000000
50%      16.000000     7.000000
75%      23.000000    10.000000
max      31.000000    12.000000

In [0]:
le_pred = LabelEncoder()

In [0]:
y = le_pred.fit_transform(data.WindDir)

In [41]:
y = np_utils.to_categorical(y)
y

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [42]:
y = y.astype('int32')
y

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int32)

In [43]:
y.shape

(4290, 8)

In [0]:
# xtrain, xtest, ytrain, ytest = train_test_split(data.iloc[:, :-1], y, test_size=0.25)

In [0]:
model = Sequential()

In [45]:
model.add(Dense(units=16, input_dim=2, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=8, activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 16)                48        
_________________________________________________________________
dense_16 (Dense)             (None, 32)                544       
_________________________________________________________________
dense_17 (Dense)             (None, 64)                2112      
_________________________________________________________________
dense_18 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_19 (Dense)             (None, 128)               8320      
_________________________________________________________________
dense_20 (Dense)             (None, 128)               16512     
_________________________________________________________________
dense_21 (Dense)             (None, 128)              

In [0]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [47]:
model.fit(data.iloc[:, :-1], y, epochs=200, batch_size=512)

Epoch 1/200
9/9 [==============================] - 0s 3ms/step - loss: 2.0653 - accuracy: 0.2455
Epoch 2/200
9/9 [==============================] - 0s 3ms/step - loss: 1.9384 - accuracy: 0.3650
Epoch 3/200
9/9 [==============================] - 0s 3ms/step - loss: 1.7770 - accuracy: 0.3650
Epoch 4/200
9/9 [==============================] - 0s 3ms/step - loss: 1.7196 - accuracy: 0.3650
Epoch 5/200
9/9 [==============================] - 0s 3ms/step - loss: 1.7055 - accuracy: 0.3650
Epoch 6/200
9/9 [==============================] - 0s 3ms/step - loss: 1.6973 - accuracy: 0.3650
Epoch 7/200
9/9 [==============================] - 0s 3ms/step - loss: 1.6910 - accuracy: 0.3650
Epoch 8/200
9/9 [==============================] - 0s 3ms/step - loss: 1.6817 - accuracy: 0.3650
Epoch 9/200
9/9 [==============================] - 0s 3ms/step - loss: 1.6763 - accuracy: 0.3650
Epoch 10/200
9/9 [==============================] - 0s 3ms/step - loss: 1.6719 - accuracy: 0.3650
Epoch 11/200
9/9 [===========

In [0]:
last_date = df['date'].iloc[-1]
last_date = datetime.datetime.strptime(last_date, "%Y-%m-%d").date()

pred_date = []
for i in range(1, 91):
    pred_date.append(last_date + datetime.timedelta(days=i))

pred_input = [[] for i in range(90)]
i = 0
for j in pred_date:
    pred_input[i].append(j.day)
    pred_input[i].append(j.month)
    i += 1

In [49]:
sample = pd.DataFrame(
    columns=['day', 'month'],
    data=pred_input
)
sample

day  month
0    30      3
1    31      3
2     1      4
3     2      4
4     3      4
..  ...    ...
85   23      6
86   24      6
87   25      6
88   26      6
89   27      6

[90 rows x 2 columns]

In [50]:
sample_p = model.predict(sample)
sample_p

array([[4.42497246e-03, 2.22043302e-02, 8.42822250e-04, 2.20614344e-01,
        6.46043122e-02, 1.45201385e-02, 2.68459260e-01, 4.04329866e-01],
       [5.11397189e-03, 2.22670771e-02, 9.54478106e-04, 2.26151228e-01,
        6.82713315e-02, 1.64848156e-02, 2.67613471e-01, 3.93143564e-01],
       [9.40424143e-05, 9.53060342e-04, 3.16396296e-07, 1.01511985e-01,
        1.24699110e-02, 9.67717147e-04, 3.18901002e-01, 5.65101981e-01],
       [2.38175267e-06, 7.62486161e-05, 6.00944072e-10, 4.34233695e-02,
        2.44121882e-03, 2.67559808e-05, 3.52486879e-01, 6.01543128e-01],
       [3.74402384e-06, 1.01678394e-04, 1.23000277e-09, 4.80431281e-02,
        2.85738078e-03, 4.64595578e-05, 3.24228972e-01, 6.24718606e-01],
       [3.09192219e-05, 3.74365132e-04, 3.33175869e-08, 6.33661821e-02,
        8.97531677e-03, 5.43772127e-04, 3.10730755e-01, 6.15978658e-01],
       [1.44342179e-04, 9.08125367e-04, 3.43376684e-07, 7.12380186e-02,
        2.48206016e-02, 3.79103445e-03, 3.44326764e-01, 5.

In [51]:
sample_pred = [0 for i in range(len(sample_p))]
for i in range(len(sample_p)):
    maxm = max(sample_p[i])
    for j in range(len(sample_p[i])):
        if sample_p[i][j] == maxm:
            index = j
    sample_pred[i] = index
print(sample_pred)

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 7, 7, 7, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 6, 6, 6, 7, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]


In [52]:
directions = le_pred.inverse_transform(sample_pred)
directions

array(['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'SW',
       'SW', 'SW', 'SW', 'W', 'W', 'W', 'SW', 'SW', 'SW', 'SW', 'SW', 'W',
       'W', 'W', 'W', 'W', 'SW', 'SW', 'SW', 'W', 'SW', 'SW', 'W', 'W',
       'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W',
       'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW',
       'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW',
       'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW',
       'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW'], dtype=object)

In [53]:
for i in range(len(directions)):
    if directions[i] == 'N':
        c = np.random.randint(0, 1)
        if c == 0:
            directions[i] = np.random.randint(0, 22.5)
        elif c == 1:
            directions[i] = np.random.randint(337.5, 360)
    elif directions[i] == 'NE':
        directions[i] = np.random.randint(22.5, 67.5)
    elif directions[i] == 'E':
        directions[i] = np.random.randint(67.5, 112.5)
    elif directions[i] == 'SE':
        directions[i] = np.random.randint(112.5, 157.5)
    elif directions[i] == 'S':
        directions[i] = np.random.randint(157.5, 202.5)
    elif directions[i] == 'SW':
        directions[i] = np.random.randint(202.5, 247.5)
    elif directions[i] == 'W':
        directions[i] = np.random.randint(247.5, 292.5)
    elif directions[i] == 'NW':
        directions[i] = np.random.randint(292.5, 337.5)
directions

array([283, 275, 286, 276, 268, 260, 288, 250, 272, 251, 251, 253, 224,
       222, 239, 238, 252, 247, 262, 207, 242, 234, 229, 240, 261, 249,
       270, 279, 287, 234, 240, 239, 282, 232, 237, 259, 288, 278, 280,
       253, 254, 260, 285, 272, 273, 258, 265, 268, 273, 280, 211, 237,
       205, 236, 204, 226, 234, 204, 231, 209, 212, 233, 207, 245, 211,
       206, 209, 203, 206, 206, 239, 219, 203, 231, 207, 226, 230, 212,
       211, 210, 230, 222, 242, 221, 234, 206, 237, 242, 245, 227],
      dtype=object)

In [0]:
pred_data = pd.DataFrame(
    columns=['date', 'direction', 'speed']
)

In [57]:
pred_data['date'] = pred_date
pred_data['direction'] = directions
pred_data

date direction speed
0   2020-03-30       283   NaN
1   2020-03-31       275   NaN
2   2020-04-01       286   NaN
3   2020-04-02       276   NaN
4   2020-04-03       268   NaN
..         ...       ...   ...
85  2020-06-23       206   NaN
86  2020-06-24       237   NaN
87  2020-06-25       242   NaN
88  2020-06-26       245   NaN
89  2020-06-27       227   NaN

[90 rows x 3 columns]

In [0]:
pred_data.to_csv('gdrive/My Drive/tarapur.csv', mode='a', header=False)