<a href="https://colab.research.google.com/github/chetan-ade/FYP/blob/master/WindDir_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
import pandas as pd
from tensorflow_core.python.keras.models import Sequential
from tensorflow_core.python.keras.layers import Activation, Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow_core.python.keras.utils import np_utils
import datetime
from datetime import date

In [22]:
location = '21.238611,73.350000'
filename = location+"_preprocessed.csv"
df = pd.read_csv(filename)
df.head()

Unnamed: 0        date  day  month WindDir  WindspeedKmph
0           0  2008-07-01    1      7      SW             17
1           1  2008-07-02    2      7      SW             21
2           2  2008-07-03    3      7      SW             18
3           3  2008-07-04    4      7      SW             17
4           4  2008-07-05    5      7      SW             18

In [23]:
data = pd.DataFrame(
    columns=['day', 'month', 'WindDir']
)

In [24]:
data['day'] = df['day']
data['month'] = df['month']
data['WindDir'] = df['WindDir']
data.head()

day  month WindDir
0    1      7      SW
1    2      7      SW
2    3      7      SW
3    4      7      SW
4    5      7      SW

In [25]:
data.describe()

day        month
count  4291.000000  4291.000000
mean     15.727336     6.556048
std       8.799939     3.476235
min       1.000000     1.000000
25%       8.000000     3.000000
50%      16.000000     7.000000
75%      23.000000    10.000000
max      31.000000    12.000000

In [26]:
le_pred = LabelEncoder()

In [27]:
y = le_pred.fit_transform(data.WindDir)

In [28]:
y = np_utils.to_categorical(y)
y

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [29]:
y = y.astype('int32')
y

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [30]:
y.shape

(4291, 8)

In [31]:
# xtrain, xtest, ytrain, ytest = train_test_split(data.iloc[:, :-1], y, test_size=0.25)

In [32]:
model = Sequential()

In [33]:
model.add(Dense(units=16, input_dim=2, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=8, activation='softmax'))
model.summary()

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                48        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_3 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_4 (Dense)              (None, 128)               8320      
_________________________________________________________________
dense_5 (Dense)              (None, 128)               16512     
_________________________________________

In [34]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [35]:
model.fit(data.iloc[:, :-1], y, epochs=200, batch_size=512)

055
Epoch 6/200
4291/4291 [==============================] - 0s 83us/sample - loss: 1.5786 - acc: 0.5055
Epoch 7/200
4291/4291 [==============================] - 0s 75us/sample - loss: 1.5649 - acc: 0.5055
Epoch 8/200
4291/4291 [==============================] - 0s 84us/sample - loss: 1.5453 - acc: 0.5055
Epoch 9/200
4291/4291 [==============================] - 0s 92us/sample - loss: 1.5216 - acc: 0.5055
Epoch 10/200
4291/4291 [==============================] - 0s 79us/sample - loss: 1.4809 - acc: 0.5055
Epoch 11/200
4291/4291 [==============================] - 0s 79us/sample - loss: 1.4511 - acc: 0.5055
Epoch 12/200
4291/4291 [==============================] - 0s 76us/sample - loss: 1.4831 - acc: 0.5055
Epoch 13/200
4291/4291 [==============================] - 0s 81us/sample - loss: 1.4071 - acc: 0.5055
Epoch 14/200
4291/4291 [==============================] - 0s 74us/sample - loss: 1.3449 - acc: 0.5192
Epoch 15/200
4291/4291 [==============================] - 0s 84us/sample - loss: 1

In [36]:
last_date = df['date'].iloc[-1]
last_date = datetime.datetime.strptime(last_date, "%Y-%m-%d").date()

pred_date = []
for i in range(1, 91):
    pred_date.append(last_date + datetime.timedelta(days=i))

pred_input = [[] for i in range(90)]
i = 0
for j in pred_date:
    pred_input[i].append(j.day)
    pred_input[i].append(j.month)
    i += 1

In [37]:
sample = pd.DataFrame(
    columns=['day', 'month'],
    data=pred_input
)
sample

day  month
0    31      3
1     1      4
2     2      4
3     3      4
4     4      4
..  ...    ...
85   24      6
86   25      6
87   26      6
88   27      6
89   28      6

[90 rows x 2 columns]

In [38]:
sample_p = model.predict(sample)
sample_p

array([[3.43493419e-03, 6.85882464e-04, 1.18432892e-02, 1.17378265e-01,
        1.14566624e-01, 2.09301561e-02, 5.07280171e-01, 2.23880678e-01],
       [3.62254708e-04, 1.10390545e-04, 2.19456619e-03, 2.65547279e-02,
        2.80102417e-02, 3.78676760e-03, 6.48921728e-01, 2.90059268e-01],
       [4.54919718e-05, 3.08840281e-05, 3.23484128e-04, 1.46854771e-02,
        7.89466407e-03, 6.02091081e-04, 6.99768066e-01, 2.76649892e-01],
       [2.52072787e-05, 2.16995086e-05, 1.80225048e-04, 1.13711134e-02,
        5.27213886e-03, 3.66972439e-04, 7.32546449e-01, 2.50216156e-01],
       [1.55815957e-04, 6.81882302e-05, 1.03796355e-03, 2.01461166e-02,
        1.62302069e-02, 1.74018077e-03, 6.62466109e-01, 2.98155397e-01],
       [3.75431497e-04, 1.20589364e-04, 2.30776332e-03, 2.39787549e-02,
        2.68031377e-02, 3.88382678e-03, 6.46708131e-01, 2.95822352e-01],
       [1.15123240e-03, 2.28985708e-04, 6.62209000e-03, 2.94831879e-02,
        5.26154712e-02, 1.13644348e-02, 6.15307212e-01, 2.

In [39]:
sample_pred = [0 for i in range(len(sample_p))]
for i in range(len(sample_p)):
    maxm = max(sample_p[i])
    for j in range(len(sample_p[i])):
        if sample_p[i][j] == maxm:
            index = j
    sample_pred[i] = index
print(sample_pred)

[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]


In [40]:
directions = le_pred.inverse_transform(sample_pred)
directions

array(['SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW',
       'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW',
       'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW',
       'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW',
       'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW',
       'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW',
       'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW',
       'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW', 'SW',
       'SW', 'SW'], dtype=object)

In [41]:
for i in range(len(directions)):
    if directions[i] == 'N':
        c = np.random.randint(0, 1)
        if c == 0:
            directions[i] = np.random.randint(0, 22.5)
        elif c == 1:
            directions[i] = np.random.randint(337.5, 360)
    elif directions[i] == 'NE':
        directions[i] = np.random.randint(22.5, 67.5)
    elif directions[i] == 'E':
        directions[i] = np.random.randint(67.5, 112.5)
    elif directions[i] == 'SE':
        directions[i] = np.random.randint(112.5, 157.5)
    elif directions[i] == 'S':
        directions[i] = np.random.randint(157.5, 202.5)
    elif directions[i] == 'SW':
        directions[i] = np.random.randint(202.5, 247.5)
    elif directions[i] == 'W':
        directions[i] = np.random.randint(247.5, 292.5)
    elif directions[i] == 'NW':
        directions[i] = np.random.randint(292.5, 337.5)
directions

array([207, 209, 216, 239, 245, 210, 222, 209, 221, 237, 230, 230, 236,
       211, 233, 209, 210, 218, 208, 236, 210, 223, 222, 208, 210, 219,
       203, 202, 228, 233, 208, 244, 206, 246, 244, 224, 235, 213, 233,
       240, 216, 217, 211, 209, 224, 219, 241, 245, 219, 225, 214, 245,
       215, 222, 209, 243, 228, 246, 202, 242, 211, 208, 224, 238, 231,
       246, 226, 228, 235, 213, 209, 220, 242, 205, 225, 206, 222, 239,
       237, 229, 244, 221, 213, 234, 246, 203, 221, 229, 219, 207],
      dtype=object)

In [42]:
pred_data = pd.DataFrame(
    columns=['date', 'direction', 'speed']
)

In [43]:
pred_data['date'] = pred_date
pred_data['direction'] = directions
pred_data

date direction speed
0   2020-03-31       207   NaN
1   2020-04-01       209   NaN
2   2020-04-02       216   NaN
3   2020-04-03       239   NaN
4   2020-04-04       245   NaN
..         ...       ...   ...
85  2020-06-24       203   NaN
86  2020-06-25       221   NaN
87  2020-06-26       229   NaN
88  2020-06-27       219   NaN
89  2020-06-28       207   NaN

[90 rows x 3 columns]

In [44]:
filename = location+".csv"
pred_data.to_csv(filename, mode='a', header=False)